import { GetStaticProps, NextPage } from 'next';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import imageLoader from '../imageLoader';
import styles from '../styles/Home.module.css'
import { Character, GetCharacterResults } from '../types'

const Home: NextPage<{characters: Character[]}> = ({characters}) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            DB_CONNECT: {process.env.NEXT_PUBLIC_DB_CONNECT}
            <hr/>
            {characters.map((char) => {
                return (
                    <div key={char.id}>
                        <Link href={`/characters/${char.id}`}>
                            <h3>{char.name}</h3>
                            <Image loader={imageLoader} unoptimized src={char.image} alt={char.name} width={200} height={200}></Image>
                        </Link>                        
                    </div>
                )
                
                
            })}
        </div>
    )
}

export const getStaticProps: GetStaticProps = async (context) => {
    const res = await fetch('https://rickandmortyapi.com/api/character');
    const { results }: GetCharacterResults = await res.json();

    return {
        props: {
            characters: results
        }
    }
}

export default Home;
